name: barbooth
title: Barbooth
version: git
summary: A simple text-based dice game
description: >
"Barbooth takes two player names, rolls two random dice and prints out the winner. 
The game features a round counter and a simple user interface. 
There are three game modes: highs, lows and classic. Project made for fun. "

confinement: strict

parts:
  barbooth: